import {
    DISCORD_WEBHOOK_URL_MESSAGES,
    DISCORD_WEBHOOK_URL_BUG_REPORTS,
    DISCORD_WEBHOOK_URL_IMPROVEMENTS,
    DISCORD_WEBHOOK_URL_FEATURES,
    DISCORD_WEBHOOK_URL_LOGS,
    DISCORD_WEBHOOK_URL_INTERNAL_ERRORS
} from '../config';

export default {
    Messages: DISCORD_WEBHOOK_URL_MESSAGES,
    BugReports: DISCORD_WEBHOOK_URL_BUG_REPORTS,
    Improvements: DISCORD_WEBHOOK_URL_IMPROVEMENTS,
    Features: DISCORD_WEBHOOK_URL_FEATURES,
    Logs: DISCORD_WEBHOOK_URL_LOGS,
    InternalErrors: DISCORD_WEBHOOK_URL_INTERNAL_ERRORS
}